language: go

go: 
 - 1.8

before_cache:
- rm -rf $GOPATH/src/github.com/zhuharev/fader-engine/*
- rm -rf $GOPATH/pkg/**/github.com/zhuharev/fader-engine

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
    - $GOPATH/bin

install:
 - go get -v github.com/Masterminds/glide
 - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.10.2 && go install && cd -
 - cd $GOPATH/src/github.com/zhuharev/fader-engine/src && GOPATH=$GOPATH/src/github.com/zhuharev/fader-engine glide i && cd -

script:
 - make test